-- SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_SALES
-- FROM BOOK B
-- JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
-- JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
-- WHERE TO_CHAR(S.SALES_DATE,'YYYY-MM')='2022-01'
-- GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
-- ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID=B.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
WHERE TO_CHAR(SALES_DATE,'YYYY-MM')='2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC








