SELECT ANIMAL_ID, NAME
FROM (
    SELECT I.ANIMAL_ID, I.NAME, (O.DATETIME-I.DATETIME) AS DAYS
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
    ORDER BY DAYS DESC)
WHERE ROWNUM<=2;