SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100) AS FEE
FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE IN ('SUV', '세단')) C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        AND TO_CHAR(H.END_DATE, 'YYYY-MM-DD') >= '2022-11-01'
        AND TO_CHAR(H.START_DATE, 'YYYY-MM-DD') < '2022-11-30'
WHERE H.CAR_ID IS NULL
    AND C.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100) >= 500000
    AND C.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;