WITH TT AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID)>=3
)

SELECT TT.WRITER_ID, U.NICKNAME, 
    U.CITY||' '||U.STREET_ADDRESS1||' '||U.STREET_ADDRESS2 AS 전체주소, 
    SUBSTR(U.TLNO,1,3)||'-'||(SUBSTR(U.TLNO,4,4))||'-'||(SUBSTR(U.TLNO,8)) AS 전화번호
FROM USED_GOODS_USER U
JOIN TT ON U.USER_ID=TT.WRITER_ID 
ORDER BY TT.WRITER_ID DESC