-- SELECT A.NAME, A.DATETIME
-- FROM (
--     SELECT ANIMAL_ID, NAME, DATETIME
--     FROM ANIMAL_INS
--     ORDER BY DATETIME ASC) A 
-- LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
-- WHERE B.ANIMAL_ID IS NULL AND ROWNUM <=3
-- ORDER BY A.DATETIME;
WITH I AS (
    SELECT *
    FROM ANIMAL_INS
    ORDER BY DATETIME)
    
SELECT I.NAME, I.DATETIME
FROM I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL AND ROWNUM<=3