-- WITH PRICE AS(
-- SELECT P.PRODUCT_ID, O.AMOUNT*P.PRICE AS PRICE
-- FROM FOOD_PRODUCT P
-- JOIN FOOD_ORDER O ON P.PRODUCT_ID=O.PRODUCT_ID
-- WHERE TO_CHAR(O.PRODUCE_DATE,'YYYY-MM')='2022-05'
-- )
-- SELECT P.PRODUCT_ID, FP.PRODUCT_NAME, SUM(P.PRICE) AS TOTAL_SALES
-- FROM PRICE P
-- JOIN FOOD_PRODUCT FP ON P.PRODUCT_ID=FP.PRODUCT_ID
-- GROUP BY P.PRODUCT_ID, FP.PRODUCT_NAME
-- ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE,'YYYY-MM')='2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID






