-- SELECT FLAVOR
-- FROM FIRST_HALF H 
-- JOIN JULY J USING (FLAVOR)
-- GROUP BY FLAVOR
-- ORDER BY SUM(H.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
-- FETCH FIRST 3 ROWS ONLY

-- SELECT FLAVOR
-- FROM FIRST_HALF FH
-- JOIN JULY J USING(FLAVOR)
-- GROUP BY FLAVOR
-- ORDER BY SUM(FH.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
-- FETCH FIRST 3 ROWS ONLY

SELECT FLAVOR
FROM FIRST_HALF H
JOIN JULY J USING(FLAVOR)
GROUP BY FLAVOR
ORDER BY SUM(H.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY