WITH TT AS(
SELECT E.EMP_NO, E.EMP_NAME, E.SAL,
CASE
    WHEN AVG(G.SCORE)>=96 THEN 'S'
    WHEN AVG(G.SCORE)>=90 THEN 'A'
    WHEN AVG(G.SCORE)>=80 THEN 'B'
    ELSE 'C'
END GRADE
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO=E.EMP_NO
GROUP BY E.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE, 
CASE
    WHEN GRADE='S' THEN SAL*0.2
    WHEN GRADE='A' THEN SAL*0.15
    WHEN GRADE='B' THEN SAL*0.1
    ELSE 0
END BONUS
FROM TT
ORDER BY EMP_NO