-- WITH NAME AS(
-- SELECT A.MEMBER_ID, A.MEMBER_NAME, COUNT(B.MEMBER_ID) AS MA
-- FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
-- GROUP BY A.MEMBER_ID, A.MEMBER_NAME
-- )

-- SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
-- FROM NAME A 
-- JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
-- WHERE A.MA >= (SELECT MAX(MA) FROM NAME)
-- ORDER BY B.REVIEW_DATE, REVIEW_TEXT;

WITH TT AS (
SELECT P.MEMBER_ID, P.MEMBER_NAME, COUNT(R.MEMBER_ID) AS MI
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P ON R.MEMBER_ID=P.MEMBER_ID
GROUP BY P.MEMBER_ID, P.MEMBER_NAME)

SELECT TT.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM TT
JOIN REST_REVIEW R ON TT.MEMBER_ID=R.MEMBER_ID
WHERE TT.MI>=(
    SELECT MAX(MI)
    FROM TT)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT