WITH NAME AS(
SELECT A.MEMBER_ID, A.MEMBER_NAME, COUNT(B.MEMBER_ID) AS MA
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY A.MEMBER_ID, A.MEMBER_NAME
)

SELECT A.MEMBER_NAME
    , B.REVIEW_TEXT
    , TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM NAME A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MA >= (SELECT MAX(MA) FROM NAME)
ORDER BY B.REVIEW_DATE, REVIEW_TEXT;