-- WITH TT AS (
-- SELECT P.MEMBER_ID, P.MEMBER_NAME, COUNT(R.MEMBER_ID) AS MI
-- FROM REST_REVIEW R
-- JOIN MEMBER_PROFILE P ON R.MEMBER_ID=P.MEMBER_ID
-- GROUP BY P.MEMBER_ID, P.MEMBER_NAME)

-- SELECT TT.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
-- FROM TT
-- JOIN REST_REVIEW R ON TT.MEMBER_ID=R.MEMBER_ID
-- WHERE TT.MI>=(
--     SELECT MAX(MI)
--     FROM TT)
-- ORDER BY REVIEW_DATE, R.REVIEW_TEXT

WITH TT AS (
SELECT P.MEMBER_ID, P.MEMBER_NAME, COUNT(R.MEMBER_ID) AS CNT
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P ON R.MEMBER_ID=P.MEMBER_ID
GROUP BY P.MEMBER_ID, P.MEMBER_NAME)

SELECT TT.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM TT
JOIN REST_REVIEW R ON TT.MEMBER_ID=R.MEMBER_ID
WHERE TT.CNT>=(SELECT MAX(CNT)
              FROM TT)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT









