WITH TT AS(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)

SELECT EXTRACT(MONTH FROM H.START_DATE) AS MONTH, TT.CAR_ID, COUNT(*) AS RECORDS
FROM TT
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON TT.CAR_ID=H.CAR_ID 
    AND TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY EXTRACT(MONTH FROM H.START_DATE), TT.CAR_ID
HAVING COUNT(*) != 0
ORDER BY MONTH, TT.CAR_ID DESC