-- WITH TAB AS (
-- SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, C.OPTIONS
-- FROM CAR_RENTAL_COMPANY_CAR C
-- WHERE C.CAR_TYPE='세단'
-- )

-- SELECT DISTINCT TAB.CAR_ID
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
-- JOIN TAB ON TAB.CAR_ID=H.CAR_ID
-- WHERE TO_CHAR(H.START_DATE,'YYYY-MM')='2022-10'
-- ORDER BY TAB.CAR_ID DESC

WITH TT AS (
SELECT *
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE = '세단')

SELECT DISTINCT(H.CAR_ID) AS CAR_ID
FROM TT
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON TT.CAR_ID=H.CAR_ID
WHERE TO_CHAR(START_DATE,'MM')='10'
ORDER BY CAR_ID DESC






