SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE) AS I2
    ON I.FISH_TYPE=I2.FISH_TYPE AND I.LENGTH=I2.MAX_LENGTH
ORDER BY I.ID ASC;