# SELECT I.ID, N.FISH_NAME, I.LENGTH
# FROM FISH_INFO I
# JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
# FROM FISH_INFO
# GROUP BY FISH_TYPE) T ON I.FISH_TYPE=T.FISH_TYPE AND I.LENGTH=T.MAX_LENGTH
# JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
# ORDER BY I.ID;

SELECT I.ID, N.FISH_NAME, T.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
JOIN ( 
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) T ON T.FISH_TYPE=I.FISH_TYPE AND T.LENGTH=I.LENGTH
ORDER BY I.ID







