SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
    CASE 
        WHEN STATUS LIKE 'SALE' THEN '판매중'
        WHEN STATUS LIKE 'RESERVED' THEN '예약중'
        WHEN STATUS LIKE 'DONE' THEN '거래완료'
    END
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE,'YYYY-MM-DD')='2022-10-05'
ORDER BY BOARD_ID DESC;